InventorySystem/InventorySystem/Models/IInventoryDBContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace InventorySystem.Models
{
  public  interface IInventoryDBContext
    {
        DbSet<Inventory> InventoryList { get; }
        int SaveChanges();
        void MarkAsModified(Inventory item);
        void Dispose();
    }
}

InventorySystem/InventorySystem/Models/Inventory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace InventorySystem.Models
{
    public class Inventory
    {
        public int ID { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z]+[ a-zA-Z-_]*$")]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        [RegularExpression(@"^-?(([1-9]\d*)|0)(.0*[1-9](0*[1-9])*)?$")]
        public decimal Price { get; set; }
    }
    public class InventoryDBContext : DbContext, IInventoryDBContext
    {
        public InventoryDBContext() : base("name=InventoryDBContext")
        {
        }
        public DbSet<Inventory> InventoryList { get; set; }
        public void MarkAsModified(Inventory item)
        {
            Entry(item).State = EntityState.Modified;
        }
        public void Dispose() { }
    }
}

InventorySystem/InventorySystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventorySystem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Root()
        {
            return RedirectToAction("Index", "Inventory");
        }
    }
}

InventorySystem/InventorySystem/Controllers/InventoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using InventorySystem.Models;

namespace InventorySystem.Controllers
{
    public class InventoriesController : ApiController
    {
        private IInventoryDBContext db = new InventoryDBContext();
        public InventoriesController() { }

        public InventoriesController(IInventoryDBContext context)
        {
            db = context;
        }
        // GET: api/Inventories
        public IQueryable<Inventory> GetInventoryList()
        {
            return db.InventoryList;
        }

        // GET: api/Inventories/5
        [ResponseType(typeof(Inventory))]
        public IHttpActionResult GetInventory(int id)
        {
            Inventory inventory = db.InventoryList.Find(id);
            if (inventory == null)
            {
                return NotFound();
            }

            return Ok(inventory);
        }

        // PUT: api/Inventories/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutInventory(int id, Inventory inventory)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != inventory.ID)
            {
                return BadRequest();
            }

            //db.Entry(inventory).State = EntityState.Modified;
            db.MarkAsModified(inventory);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!InventoryExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Inventories
        [ResponseType(typeof(Inventory))]
        public IHttpActionResult PostInventory(Inventory inventory)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.InventoryList.Add(inventory);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = inventory.ID }, inventory);
        }

        // DELETE: api/Inventories/5
        [ResponseType(typeof(Inventory))]
        public IHttpActionResult DeleteInventory(int id)
        {
            Inventory inventory = db.InventoryList.Find(id);
            if (inventory == null)
            {
                return NotFound();
            }

            db.InventoryList.Remove(inventory);
            db.SaveChanges();

            return Ok(inventory);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool InventoryExists(int id)
        {
            return db.InventoryList.Count(e => e.ID == id) > 0;
        }
    }
}

InventorySystem/InventorySystem/Controllers/InventoryController.cs
using InventorySystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace InventorySystem.Controllers
{
    public class InventoryController : Controller
    {
        /// <summary>
        /// GET: Index
        /// </summary>
        /// <returns>ActionResult</returns>
        public async Task<ActionResult> Index()
        {
            //string url = HttpContext.Request.Url.Authority;
            IEnumerable<Inventory> InventoryList = null;
            var client = new HttpClient();
            var response = await client.GetAsync("http://localhost:59915//api/Inventories");  //making call to WebAPI
            if (response.IsSuccessStatusCode)
            {
                InventoryList = await response.Content.ReadAsAsync<IEnumerable<Inventory>>(); //fetchimg data
            }
            else
            {
                return RedirectToAction("Error", "NotFound");  //Redirect to error page
            }
            return View(InventoryList.ToList());

        }
    }
}

InventorySystem/InventorySystem/Controllers/ItemDetailController.cs
using InventorySystem.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace InventorySystem.Controllers
{
    public class ItemDetailController : Controller
    {
        /// <summary>
        /// GET: Detail
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns>ActionResult</returns>
        public async Task<ActionResult>Detail(int id)
        {
            //string url = HttpContext.Request.Url.Authority;
            Inventory InventoryList = null;
            var client = new HttpClient();
            var response = await client.GetAsync("http://localhost:59915/api/Inventories/"+id);   //making call to WebAPI
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;   //fetchimg data
                InventoryList = JsonConvert.DeserializeObject<Inventory>(data);

            }
            else
            {
                 return RedirectToAction("Error", "NotFound");  //Redirect to error page

            }

            return View(InventoryList);

        }
    }
}

InventorySystem/InventorySystem/Controllers/NotFoundController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventorySystem.Controllers
{
    public class NotFoundController : Controller
    {
        // GET: NotFound
        public ActionResult Error()
        {
            return View("Error");
        }
    }
}

InventorySystem/InventorySystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

InventorySystem/InventorySystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

InventorySystem/InventorySystem/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

InventorySystem/InventorySystem/Views/Inventory/Index.cshtml
@model IEnumerable<InventorySystem.Models.Inventory>

@{
    ViewBag.Title = "Create";
}
<div ID="errorMessage" class="alert alert-warning error-message" ></div>
<div class="form-horizontal center">
    <table>
        <caption><h3>Create Inventory</h3></caption>
        <tbody>
            
            <tr>
                <div class="form-group" align="left" valign="top">
                    <td colspan="3" class="p-3">
                        <asp-label>Name:</asp-label>
                    </td>
                    <td colspan="3" align="left" valign="top" class="p-3">
                        <div class="col-md-10">
                            <input type="text" id="name" class="form-control" required />
                        </div>
                    </td>
                </div>
            </tr>
            <tr>
                <div class="form-group">
                    <td colspan="3" class="p-3">
                        <asp-label>Description:</asp-label>
                    </td>
                    <td colspan="3" class="p-3">
                        <div class="col-md-10">
                            <input type="text" id="description" class="form-control" required />
                        </div>
                    </td>
                </div>
            </tr>
            <tr>
                <div class="form-group">
                    <td colspan="3" class="p-3">
                        <asp-label>Price:</asp-label>
                    </td>
                    <td colspan="3" class="p-3">
                        <div class="col-md-10">
                            <input type="number" id="price" class="form-control" min="1" required />
                        </div>
                    </td>
                </div>
            </tr>
            <tr>
                <div class="form-group">
                    <td colspan="3" class="p-3"></td>
                    <td colspan="3" class="p-3">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="button" value="Add Item" class="btn btn-default" onclick="create()" />
                        </div>
                    </td>
                </div>
            </tr>
        </tbody>
    </table>
</div>

<div class="center">
     <table class="table" id="InventoryList">
        <caption><h3>Item List</h3></caption>
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                        </td>
                    <td>
                        <a href='@Url.Action("Detail","ItemDetail", new { id = item.ID })'>Details</a>
                        <button class="btn btn-default" ID="@item.ID" onclick="removeItemFromList(this.id)" style="margin-left:7px">
                            <i class="material-icons">delete</i>
                        </button>
                    </td>
                   

                </tr>

            }
        </tbody>

    </table>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InventorySystem/InventorySystem/Views/ItemDetail/Detail.cshtml
@model InventorySystem.Models.Inventory

@{
    ViewBag.Title = "Details";
}
<div class="detail">
    <table class="table table-bordered ">
        <tbody>
          <tr>
                <td class="bolder">
                    @Html.DisplayNameFor(model => model.Name)
                </td>
                <td>
                    @Model.Name
                </td>
            </tr>
            <tr>
                <td class="bolder">
                    @Html.DisplayNameFor(model => model.Description)
                </td>
                <td>
                    @Model.Description
                </td>
            </tr>
            <tr>
                <td class="bolder">
                    @Html.DisplayNameFor(model => model.Price)
                </td>
                <td>
                    @Model.Price
                </td>
            </tr>
        </tbody>
      </table>
</div>
<div class="navigate-back bolder">
    <a href='@Url.Action("Index","Inventory")'>Click here to return back</a>
</div>

InventorySystem/InventorySystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Inventory App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inventory App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -Inventory App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>